### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 8

### ISSUE THREAD

**Issue by i3ym** [tiffit/DungeonDimension#2]
http://pastebin.com/Gkqb1fzY

**Comment by tiffit** [comment]
This is not a problem with my mod but instead one with the "CustomColors" mod

**Comment by i3ym** [comment]
But I don't have this mod...

**Comment by tiffit** [comment]
Do you have any mods that change/alter the sky in any way?

**Comment by i3ym** [comment]
No, but..
Maybe, Optifine?
I have a resource pack that change sky..

**Comment by tiffit** [comment]
Do you still get this error when you remove all other mods?

**Comment by i3ym** [comment]
No, all working..

**Comment by tiffit** [comment]
Then the problem is most likely not from my mod but instead a different one
